<?php

/**
 * BaseBlogRssCache
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property string $title
 * @property string $description
 * @property string $link
 * @property timestamp $date
 * @property Member $Member
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getMemberId()    Returns the current record's "member_id" value
 * @method string       getTitle()       Returns the current record's "title" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method string       getLink()        Returns the current record's "link" value
 * @method timestamp    getDate()        Returns the current record's "date" value
 * @method Member       getMember()      Returns the current record's "Member" value
 * @method BlogRssCache setId()          Sets the current record's "id" value
 * @method BlogRssCache setMemberId()    Sets the current record's "member_id" value
 * @method BlogRssCache setTitle()       Sets the current record's "title" value
 * @method BlogRssCache setDescription() Sets the current record's "description" value
 * @method BlogRssCache setLink()        Sets the current record's "link" value
 * @method BlogRssCache setDate()        Sets the current record's "date" value
 * @method BlogRssCache setMember()      Sets the current record's "Member" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBlogRssCache extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_rss_cache');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('link', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('date_INDEX', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}