<?php

/**
 * BaseMemberProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $profile_id
 * @property integer $profile_option_id
 * @property string $value
 * @property timestamp $value_datetime
 * @property integer $public_flag
 * @property Member $Member
 * @property Profile $Profile
 * @property ProfileOption $ProfileOption
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method integer       getMemberId()          Returns the current record's "member_id" value
 * @method integer       getProfileId()         Returns the current record's "profile_id" value
 * @method integer       getProfileOptionId()   Returns the current record's "profile_option_id" value
 * @method string        getValue()             Returns the current record's "value" value
 * @method timestamp     getValueDatetime()     Returns the current record's "value_datetime" value
 * @method integer       getPublicFlag()        Returns the current record's "public_flag" value
 * @method Member        getMember()            Returns the current record's "Member" value
 * @method Profile       getProfile()           Returns the current record's "Profile" value
 * @method ProfileOption getProfileOption()     Returns the current record's "ProfileOption" value
 * @method MemberProfile setId()                Sets the current record's "id" value
 * @method MemberProfile setMemberId()          Sets the current record's "member_id" value
 * @method MemberProfile setProfileId()         Sets the current record's "profile_id" value
 * @method MemberProfile setProfileOptionId()   Sets the current record's "profile_option_id" value
 * @method MemberProfile setValue()             Sets the current record's "value" value
 * @method MemberProfile setValueDatetime()     Sets the current record's "value_datetime" value
 * @method MemberProfile setPublicFlag()        Sets the current record's "public_flag" value
 * @method MemberProfile setMember()            Sets the current record's "Member" value
 * @method MemberProfile setProfile()           Sets the current record's "Profile" value
 * @method MemberProfile setProfileOption()     Sets the current record's "ProfileOption" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMemberProfile extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Member id',
             'length' => '4',
             ));
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Profile id',
             'length' => '4',
             ));
        $this->hasColumn('profile_option_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'Profile option id',
             'length' => '4',
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'Text content for this profile item',
             ));
        $this->hasColumn('value_datetime', 'timestamp', null, array(
             'type' => 'timestamp',
             'comment' => 'Profile datetime value',
             ));
        $this->hasColumn('public_flag', 'integer', 1, array(
             'type' => 'integer',
             'comment' => 'Public flag',
             'length' => '1',
             ));


        $this->index('lft_INDEX', array(
             'fields' => 
             array(
              0 => 'lft',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves informations of every member\'\'s profile');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ProfileOption', array(
             'local' => 'profile_option_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'tree_key',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($nestedset0);
        $this->actAs($timestampable0);
    }
}