<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property integer $filesize
 * @property string $original_filename
 * @property Doctrine_Collection $Albums
 * @property Doctrine_Collection $AlbumImages
 * @property Doctrine_Collection $DiaryImages
 * @property Doctrine_Collection $DiaryCommentImages
 * @property Doctrine_Collection $MessageFile
 * @property Doctrine_Collection $MemberImage
 * @property FileBin $FileBin
 * @property Doctrine_Collection $Community
 * @property Doctrine_Collection $OAuthConsumerInformation
 * @property Doctrine_Collection $BannerImage
 * @property Doctrine_Collection $ActivityImage
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method string              getType()                     Returns the current record's "type" value
 * @method integer             getFilesize()                 Returns the current record's "filesize" value
 * @method string              getOriginalFilename()         Returns the current record's "original_filename" value
 * @method Doctrine_Collection getAlbums()                   Returns the current record's "Albums" collection
 * @method Doctrine_Collection getAlbumImages()              Returns the current record's "AlbumImages" collection
 * @method Doctrine_Collection getDiaryImages()              Returns the current record's "DiaryImages" collection
 * @method Doctrine_Collection getDiaryCommentImages()       Returns the current record's "DiaryCommentImages" collection
 * @method Doctrine_Collection getMessageFile()              Returns the current record's "MessageFile" collection
 * @method Doctrine_Collection getMemberImage()              Returns the current record's "MemberImage" collection
 * @method FileBin             getFileBin()                  Returns the current record's "FileBin" value
 * @method Doctrine_Collection getCommunity()                Returns the current record's "Community" collection
 * @method Doctrine_Collection getOAuthConsumerInformation() Returns the current record's "OAuthConsumerInformation" collection
 * @method Doctrine_Collection getBannerImage()              Returns the current record's "BannerImage" collection
 * @method Doctrine_Collection getActivityImage()            Returns the current record's "ActivityImage" collection
 * @method File                setId()                       Sets the current record's "id" value
 * @method File                setName()                     Sets the current record's "name" value
 * @method File                setType()                     Sets the current record's "type" value
 * @method File                setFilesize()                 Sets the current record's "filesize" value
 * @method File                setOriginalFilename()         Sets the current record's "original_filename" value
 * @method File                setAlbums()                   Sets the current record's "Albums" collection
 * @method File                setAlbumImages()              Sets the current record's "AlbumImages" collection
 * @method File                setDiaryImages()              Sets the current record's "DiaryImages" collection
 * @method File                setDiaryCommentImages()       Sets the current record's "DiaryCommentImages" collection
 * @method File                setMessageFile()              Sets the current record's "MessageFile" collection
 * @method File                setMemberImage()              Sets the current record's "MemberImage" collection
 * @method File                setFileBin()                  Sets the current record's "FileBin" value
 * @method File                setCommunity()                Sets the current record's "Community" collection
 * @method File                setOAuthConsumerInformation() Sets the current record's "OAuthConsumerInformation" collection
 * @method File                setBannerImage()              Sets the current record's "BannerImage" collection
 * @method File                setActivityImage()            Sets the current record's "ActivityImage" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFile extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'File name',
             'length' => '64',
             ));
        $this->hasColumn('type', 'string', 64, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'Type of this file',
             'length' => '64',
             ));
        $this->hasColumn('filesize', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'comment' => 'File size',
             'length' => '4',
             ));
        $this->hasColumn('original_filename', 'string', null, array(
             'type' => 'string',
             'comment' => 'Original filename',
             ));


        $this->index('name_UNIQUE', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves informations of files uploaded');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Album as Albums', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('AlbumImage as AlbumImages', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('DiaryImage as DiaryImages', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('DiaryCommentImage as DiaryCommentImages', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('MessageFile', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('MemberImage', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasOne('FileBin', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('Community', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('OAuthConsumerInformation', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('BannerImage', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('ActivityImage', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}