<?php

/**
 * BaseCommunityCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $is_allow_member_community
 * @property integer $tree_key
 * @property integer $sort_order
 * @property Doctrine_Collection $Community
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method string              getName()                      Returns the current record's "name" value
 * @method boolean             getIsAllowMemberCommunity()    Returns the current record's "is_allow_member_community" value
 * @method integer             getTreeKey()                   Returns the current record's "tree_key" value
 * @method integer             getSortOrder()                 Returns the current record's "sort_order" value
 * @method Doctrine_Collection getCommunity()                 Returns the current record's "Community" collection
 * @method CommunityCategory   setId()                        Sets the current record's "id" value
 * @method CommunityCategory   setName()                      Sets the current record's "name" value
 * @method CommunityCategory   setIsAllowMemberCommunity()    Sets the current record's "is_allow_member_community" value
 * @method CommunityCategory   setTreeKey()                   Sets the current record's "tree_key" value
 * @method CommunityCategory   setSortOrder()                 Sets the current record's "sort_order" value
 * @method CommunityCategory   setCommunity()                 Sets the current record's "Community" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommunityCategory extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'Category name',
             'length' => '64',
             ));
        $this->hasColumn('is_allow_member_community', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             'comment' => 'Member can create this category community',
             ));
        $this->hasColumn('tree_key', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'Nested tree key',
             'length' => '4',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'Order to sort',
             'length' => '4',
             ));


        $this->index('lft_INDEX', array(
             'fields' => 
             array(
              0 => 'lft',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves categories of community');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Community', array(
             'local' => 'id',
             'foreign' => 'community_category_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'tree_key',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($nestedset0);
        $this->actAs($timestampable0);
    }
}