<?php

/**
 * BaseActivityImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $activity_data_id
 * @property string $mime_type
 * @property string $uri
 * @property integer $file_id
 * @property ActivityData $ActivityData
 * @property File $File
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method integer       getActivityDataId()   Returns the current record's "activity_data_id" value
 * @method string        getMimeType()         Returns the current record's "mime_type" value
 * @method string        getUri()              Returns the current record's "uri" value
 * @method integer       getFileId()           Returns the current record's "file_id" value
 * @method ActivityData  getActivityData()     Returns the current record's "ActivityData" value
 * @method File          getFile()             Returns the current record's "File" value
 * @method ActivityImage setId()               Sets the current record's "id" value
 * @method ActivityImage setActivityDataId()   Sets the current record's "activity_data_id" value
 * @method ActivityImage setMimeType()         Sets the current record's "mime_type" value
 * @method ActivityImage setUri()              Sets the current record's "uri" value
 * @method ActivityImage setFileId()           Sets the current record's "file_id" value
 * @method ActivityImage setActivityData()     Sets the current record's "ActivityData" value
 * @method ActivityImage setFile()             Sets the current record's "File" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActivityImage extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('activity_data_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Activity data id',
             'length' => '4',
             ));
        $this->hasColumn('mime_type', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'MIME type',
             'length' => '64',
             ));
        $this->hasColumn('uri', 'string', null, array(
             'type' => 'string',
             'comment' => 'Image URI',
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'comment' => 'File id',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves image information of activity');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActivityData', array(
             'local' => 'activity_data_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}