<?php

/**
 * BasePlugin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $is_enabled
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method boolean getIsEnabled()  Returns the current record's "is_enabled" value
 * @method Plugin  setId()         Sets the current record's "id" value
 * @method Plugin  setName()       Sets the current record's "name" value
 * @method Plugin  setIsEnabled()  Sets the current record's "is_enabled" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePlugin extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plugin');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'Nickname',
             'length' => '64',
             ));
        $this->hasColumn('is_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             'comment' => 'Notification Enabled',
             ));


        $this->index('is_enabled_INDEX', array(
             'fields' => 
             array(
              0 => 'is_enabled',
             ),
             ));
        $this->index('name_UNIQUE', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves informations of plugins');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}