<?php

/**
 * BaseBannerImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $file_id
 * @property string $url
 * @property string $name
 * @property File $File
 * @property Doctrine_Collection $BannerUseImage
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getFileId()         Returns the current record's "file_id" value
 * @method string              getUrl()            Returns the current record's "url" value
 * @method string              getName()           Returns the current record's "name" value
 * @method File                getFile()           Returns the current record's "File" value
 * @method Doctrine_Collection getBannerUseImage() Returns the current record's "BannerUseImage" collection
 * @method BannerImage         setId()             Sets the current record's "id" value
 * @method BannerImage         setFileId()         Sets the current record's "file_id" value
 * @method BannerImage         setUrl()            Sets the current record's "url" value
 * @method BannerImage         setName()           Sets the current record's "name" value
 * @method BannerImage         setFile()           Sets the current record's "File" value
 * @method BannerImage         setBannerUseImage() Sets the current record's "BannerUseImage" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBannerImage extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'An image\'\'s file id',
             'length' => '4',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'comment' => 'URL of linked Web page',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'comment' => 'Banner image name',
             'length' => '64',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves informations about banner image files');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('BannerUseImage', array(
             'local' => 'id',
             'foreign' => 'banner_image_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}