<?php

/**
 * BaseCommunityMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $community_id
 * @property integer $member_id
 * @property boolean $is_pre
 * @property boolean $is_receive_mail_pc
 * @property boolean $is_receive_mail_mobile
 * @property Community $Community
 * @property Member $Member
 * @property Doctrine_Collection $CommunityMemberPosition
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method integer             getCommunityId()             Returns the current record's "community_id" value
 * @method integer             getMemberId()                Returns the current record's "member_id" value
 * @method boolean             getIsPre()                   Returns the current record's "is_pre" value
 * @method boolean             getIsReceiveMailPc()         Returns the current record's "is_receive_mail_pc" value
 * @method boolean             getIsReceiveMailMobile()     Returns the current record's "is_receive_mail_mobile" value
 * @method Community           getCommunity()               Returns the current record's "Community" value
 * @method Member              getMember()                  Returns the current record's "Member" value
 * @method Doctrine_Collection getCommunityMemberPosition() Returns the current record's "CommunityMemberPosition" collection
 * @method CommunityMember     setId()                      Sets the current record's "id" value
 * @method CommunityMember     setCommunityId()             Sets the current record's "community_id" value
 * @method CommunityMember     setMemberId()                Sets the current record's "member_id" value
 * @method CommunityMember     setIsPre()                   Sets the current record's "is_pre" value
 * @method CommunityMember     setIsReceiveMailPc()         Sets the current record's "is_receive_mail_pc" value
 * @method CommunityMember     setIsReceiveMailMobile()     Sets the current record's "is_receive_mail_mobile" value
 * @method CommunityMember     setCommunity()               Sets the current record's "Community" value
 * @method CommunityMember     setMember()                  Sets the current record's "Member" value
 * @method CommunityMember     setCommunityMemberPosition() Sets the current record's "CommunityMemberPosition" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommunityMember extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_member');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Community id',
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Member id',
             'length' => '4',
             ));
        $this->hasColumn('is_pre', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Is pre member?',
             ));
        $this->hasColumn('is_receive_mail_pc', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             'comment' => 'Notification of posting in community by computer E-mail.',
             ));
        $this->hasColumn('is_receive_mail_mobile', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             'comment' => 'Notification of posting in community by mobile E-mail.',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves informations of members joined');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Community', array(
             'local' => 'community_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('CommunityMemberPosition', array(
             'local' => 'id',
             'foreign' => 'community_member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}