<?php

/**
 * BaseFileBin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property blob $bin
 * @property File $File
 * 
 * @method integer getFileId()  Returns the current record's "file_id" value
 * @method blob    getBin()     Returns the current record's "bin" value
 * @method File    getFile()    Returns the current record's "File" value
 * @method FileBin setFileId()  Sets the current record's "file_id" value
 * @method FileBin setBin()     Sets the current record's "bin" value
 * @method FileBin setFile()    Sets the current record's "File" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFileBin extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_bin');
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'comment' => 'File id',
             'length' => '4',
             ));
        $this->hasColumn('bin', 'blob', null, array(
             'type' => 'blob',
             'comment' => 'Content of file',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves content of files');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'owningSide' => true));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}