<?php

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $data
 * @property string $time
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method string  getData() Returns the current record's "data" value
 * @method string  getTime() Returns the current record's "time" value
 * @method Session setId()   Sets the current record's "id" value
 * @method Session setData() Sets the current record's "data" value
 * @method Session setTime() Sets the current record's "time" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSession extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('data', 'string', null, array(
             'type' => 'string',
             'comment' => 'Session information',
             ));
        $this->hasColumn('time', 'string', null, array(
             'type' => 'string',
             'comment' => 'Timestamp of generated time',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves session data');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}