<?php

/**
 * BaseCommunityMemberPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $community_id
 * @property integer $member_id
 * @property integer $community_member_id
 * @property string $name
 * @property Community $Community
 * @property Member $Member
 * @property CommunityMember $CommunityMember
 * 
 * @method integer                 getId()                  Returns the current record's "id" value
 * @method integer                 getCommunityId()         Returns the current record's "community_id" value
 * @method integer                 getMemberId()            Returns the current record's "member_id" value
 * @method integer                 getCommunityMemberId()   Returns the current record's "community_member_id" value
 * @method string                  getName()                Returns the current record's "name" value
 * @method Community               getCommunity()           Returns the current record's "Community" value
 * @method Member                  getMember()              Returns the current record's "Member" value
 * @method CommunityMember         getCommunityMember()     Returns the current record's "CommunityMember" value
 * @method CommunityMemberPosition setId()                  Sets the current record's "id" value
 * @method CommunityMemberPosition setCommunityId()         Sets the current record's "community_id" value
 * @method CommunityMemberPosition setMemberId()            Sets the current record's "member_id" value
 * @method CommunityMemberPosition setCommunityMemberId()   Sets the current record's "community_member_id" value
 * @method CommunityMemberPosition setName()                Sets the current record's "name" value
 * @method CommunityMemberPosition setCommunity()           Sets the current record's "Community" value
 * @method CommunityMemberPosition setMember()              Sets the current record's "Member" value
 * @method CommunityMemberPosition setCommunityMember()     Sets the current record's "CommunityMember" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommunityMemberPosition extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_member_position');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Community id',
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Member id',
             'length' => '4',
             ));
        $this->hasColumn('community_member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Community Member id',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Member\'\'s position name in this community',
             'length' => '32',
             ));


        $this->index('name_UNIQUE', array(
             'fields' => 
             array(
              0 => 'community_member_id',
              1 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves informations of the Community\'\'s member roles');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Community', array(
             'local' => 'community_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('CommunityMember', array(
             'local' => 'community_member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}