<?php

/**
 * BaseMemberImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $file_id
 * @property boolean $is_primary
 * @property Member $Member
 * @property File $File
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getMemberId()   Returns the current record's "member_id" value
 * @method integer     getFileId()     Returns the current record's "file_id" value
 * @method boolean     getIsPrimary()  Returns the current record's "is_primary" value
 * @method Member      getMember()     Returns the current record's "Member" value
 * @method File        getFile()       Returns the current record's "File" value
 * @method MemberImage setId()         Sets the current record's "id" value
 * @method MemberImage setMemberId()   Sets the current record's "member_id" value
 * @method MemberImage setFileId()     Sets the current record's "file_id" value
 * @method MemberImage setIsPrimary()  Sets the current record's "is_primary" value
 * @method MemberImage setMember()     Sets the current record's "Member" value
 * @method MemberImage setFile()       Sets the current record's "File" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMemberImage extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Member id',
             'length' => '4',
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Image file id in the \'\'file\'\' table',
             'length' => '4',
             ));
        $this->hasColumn('is_primary', 'boolean', null, array(
             'type' => 'boolean',
             'comment' => 'This is primary',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves images in member profiles');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}