<?php

/**
 * BaseOpenIDTrustLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property string $uri
 * @property string $uri_key
 * @property boolean $is_permanent
 * @property Member $Member
 * 
 * @method integer        getId()           Returns the current record's "id" value
 * @method integer        getMemberId()     Returns the current record's "member_id" value
 * @method string         getUri()          Returns the current record's "uri" value
 * @method string         getUriKey()       Returns the current record's "uri_key" value
 * @method boolean        getIsPermanent()  Returns the current record's "is_permanent" value
 * @method Member         getMember()       Returns the current record's "Member" value
 * @method OpenIDTrustLog setId()           Sets the current record's "id" value
 * @method OpenIDTrustLog setMemberId()     Sets the current record's "member_id" value
 * @method OpenIDTrustLog setUri()          Sets the current record's "uri" value
 * @method OpenIDTrustLog setUriKey()       Sets the current record's "uri_key" value
 * @method OpenIDTrustLog setIsPermanent()  Sets the current record's "is_permanent" value
 * @method OpenIDTrustLog setMember()       Sets the current record's "Member" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOpenIDTrustLog extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('openid_trust_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'Member id',
             'length' => '4',
             ));
        $this->hasColumn('uri', 'string', null, array(
             'type' => 'string',
             'comment' => 'URI for RP',
             ));
        $this->hasColumn('uri_key', 'string', 32, array(
             'type' => 'string',
             'comment' => 'Hashed URI for RP',
             'length' => '32',
             ));
        $this->hasColumn('is_permanent', 'boolean', null, array(
             'type' => 'boolean',
             'comment' => 'A permanent flag',
             ));


        $this->index('uri_key_INDEX', array(
             'fields' => 
             array(
              0 => 'uri_key',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves logs of trusted OpenID RP');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}