<?php

/**
 * BaseMemberRelationship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id_to
 * @property integer $member_id_from
 * @property boolean $is_friend
 * @property boolean $is_friend_pre
 * @property boolean $is_access_block
 * @property Member $Member
 * @property Member $MemberRelatedByMemberIdFrom
 * 
 * @method integer            getId()                          Returns the current record's "id" value
 * @method integer            getMemberIdTo()                  Returns the current record's "member_id_to" value
 * @method integer            getMemberIdFrom()                Returns the current record's "member_id_from" value
 * @method boolean            getIsFriend()                    Returns the current record's "is_friend" value
 * @method boolean            getIsFriendPre()                 Returns the current record's "is_friend_pre" value
 * @method boolean            getIsAccessBlock()               Returns the current record's "is_access_block" value
 * @method Member             getMember()                      Returns the current record's "Member" value
 * @method Member             getMemberRelatedByMemberIdFrom() Returns the current record's "MemberRelatedByMemberIdFrom" value
 * @method MemberRelationship setId()                          Sets the current record's "id" value
 * @method MemberRelationship setMemberIdTo()                  Sets the current record's "member_id_to" value
 * @method MemberRelationship setMemberIdFrom()                Sets the current record's "member_id_from" value
 * @method MemberRelationship setIsFriend()                    Sets the current record's "is_friend" value
 * @method MemberRelationship setIsFriendPre()                 Sets the current record's "is_friend_pre" value
 * @method MemberRelationship setIsAccessBlock()               Sets the current record's "is_access_block" value
 * @method MemberRelationship setMember()                      Sets the current record's "Member" value
 * @method MemberRelationship setMemberRelatedByMemberIdFrom() Sets the current record's "MemberRelatedByMemberIdFrom" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMemberRelationship extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_relationship');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('member_id_to', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Target member id',
             'length' => '4',
             ));
        $this->hasColumn('member_id_from', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Subject member id',
             'length' => '4',
             ));
        $this->hasColumn('is_friend', 'boolean', null, array(
             'type' => 'boolean',
             'comment' => 'The members are friends',
             ));
        $this->hasColumn('is_friend_pre', 'boolean', null, array(
             'type' => 'boolean',
             'comment' => 'The members are going to be friends',
             ));
        $this->hasColumn('is_access_block', 'boolean', null, array(
             'type' => 'boolean',
             'comment' => 'The subject member is blocked the target',
             ));


        $this->index('member_id_to_from_UNIQUE', array(
             'fields' => 
             array(
              0 => 'member_id_to',
              1 => 'member_id_from',
             ),
             'type' => 'unique',
             ));
        $this->index('member_id_from_to_UNIQUE', array(
             'fields' => 
             array(
              0 => 'member_id_from',
              1 => 'member_id_to',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves ralationships of each members');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id_to',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member as MemberRelatedByMemberIdFrom', array(
             'local' => 'member_id_from',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $opactivitycascadingbehavior0 = new opActivityCascadingBehavior();
        $this->actAs($timestampable0);
        $this->actAs($opactivitycascadingbehavior0);
    }
}