<?php

/**
 * BaseMemberConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property string $name
 * @property string $value
 * @property timestamp $value_datetime
 * @property string $name_value_hash
 * @property Member $Member
 * 
 * @method integer      getId()              Returns the current record's "id" value
 * @method integer      getMemberId()        Returns the current record's "member_id" value
 * @method string       getName()            Returns the current record's "name" value
 * @method string       getValue()           Returns the current record's "value" value
 * @method timestamp    getValueDatetime()   Returns the current record's "value_datetime" value
 * @method string       getNameValueHash()   Returns the current record's "name_value_hash" value
 * @method Member       getMember()          Returns the current record's "Member" value
 * @method MemberConfig setId()              Sets the current record's "id" value
 * @method MemberConfig setMemberId()        Sets the current record's "member_id" value
 * @method MemberConfig setName()            Sets the current record's "name" value
 * @method MemberConfig setValue()           Sets the current record's "value" value
 * @method MemberConfig setValueDatetime()   Sets the current record's "value_datetime" value
 * @method MemberConfig setNameValueHash()   Sets the current record's "name_value_hash" value
 * @method MemberConfig setMember()          Sets the current record's "Member" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMemberConfig extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_config');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'Serial number',
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Member id',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'Configuration name',
             'length' => '64',
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'default' => '',
             'notnull' => true,
             'comment' => 'Configuration value',
             ));
        $this->hasColumn('value_datetime', 'timestamp', null, array(
             'type' => 'timestamp',
             'comment' => 'Configuration datetime value',
             ));
        $this->hasColumn('name_value_hash', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Hash value for searching name & value',
             'length' => '32',
             ));


        $this->index('name_INDEX', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->index('name_value_hash_INDEX', array(
             'fields' => 
             array(
              0 => 'name_value_hash',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'Saves configurations of each members');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}