<?php

/**
 * BaseAlbumImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $album_id
 * @property integer $member_id
 * @property integer $file_id
 * @property string $description
 * @property integer $filesize
 * @property Album $Album
 * @property File $File
 * @property Member $Member
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getAlbumId()     Returns the current record's "album_id" value
 * @method integer    getMemberId()    Returns the current record's "member_id" value
 * @method integer    getFileId()      Returns the current record's "file_id" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method integer    getFilesize()    Returns the current record's "filesize" value
 * @method Album      getAlbum()       Returns the current record's "Album" value
 * @method File       getFile()        Returns the current record's "File" value
 * @method Member     getMember()      Returns the current record's "Member" value
 * @method AlbumImage setId()          Sets the current record's "id" value
 * @method AlbumImage setAlbumId()     Sets the current record's "album_id" value
 * @method AlbumImage setMemberId()    Sets the current record's "member_id" value
 * @method AlbumImage setFileId()      Sets the current record's "file_id" value
 * @method AlbumImage setDescription() Sets the current record's "description" value
 * @method AlbumImage setFilesize()    Sets the current record's "filesize" value
 * @method AlbumImage setAlbum()       Sets the current record's "Album" value
 * @method AlbumImage setFile()        Sets the current record's "File" value
 * @method AlbumImage setMember()      Sets the current record's "Member" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAlbumImage extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('album_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '4',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('filesize', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}