<?php

/**
 * BaseCommunityEventMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $community_event_id
 * @property integer $member_id
 * @property Member $Member
 * @property CommunityEvent $CommunityEvent
 * 
 * @method integer              getId()                 Returns the current record's "id" value
 * @method integer              getCommunityEventId()   Returns the current record's "community_event_id" value
 * @method integer              getMemberId()           Returns the current record's "member_id" value
 * @method Member               getMember()             Returns the current record's "Member" value
 * @method CommunityEvent       getCommunityEvent()     Returns the current record's "CommunityEvent" value
 * @method CommunityEventMember setId()                 Sets the current record's "id" value
 * @method CommunityEventMember setCommunityEventId()   Sets the current record's "community_event_id" value
 * @method CommunityEventMember setMemberId()           Sets the current record's "member_id" value
 * @method CommunityEventMember setMember()             Sets the current record's "Member" value
 * @method CommunityEventMember setCommunityEvent()     Sets the current record's "CommunityEvent" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommunityEventMember extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_event_member');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('community_event_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('CommunityEvent', array(
             'local' => 'community_event_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}