<?php

/**
 * BaseCommunityTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $community_id
 * @property integer $member_id
 * @property string $name
 * @property string $body
 * @property timestamp $topic_updated_at
 * @property Member $Member
 * @property Community $Community
 * @property Doctrine_Collection $CommunityTopicComment
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getCommunityId()           Returns the current record's "community_id" value
 * @method integer             getMemberId()              Returns the current record's "member_id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getBody()                  Returns the current record's "body" value
 * @method timestamp           getTopicUpdatedAt()        Returns the current record's "topic_updated_at" value
 * @method Member              getMember()                Returns the current record's "Member" value
 * @method Community           getCommunity()             Returns the current record's "Community" value
 * @method Doctrine_Collection getCommunityTopicComment() Returns the current record's "CommunityTopicComment" collection
 * @method CommunityTopic      setId()                    Sets the current record's "id" value
 * @method CommunityTopic      setCommunityId()           Sets the current record's "community_id" value
 * @method CommunityTopic      setMemberId()              Sets the current record's "member_id" value
 * @method CommunityTopic      setName()                  Sets the current record's "name" value
 * @method CommunityTopic      setBody()                  Sets the current record's "body" value
 * @method CommunityTopic      setTopicUpdatedAt()        Sets the current record's "topic_updated_at" value
 * @method CommunityTopic      setMember()                Sets the current record's "Member" value
 * @method CommunityTopic      setCommunity()             Sets the current record's "Community" value
 * @method CommunityTopic      setCommunityTopicComment() Sets the current record's "CommunityTopicComment" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommunityTopic extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_topic');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('topic_updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Community', array(
             'local' => 'community_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('CommunityTopicComment', array(
             'local' => 'id',
             'foreign' => 'community_topic_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}