<?php

/**
 * BaseAshiato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id_from
 * @property integer $member_id_to
 * @property date $r_date
 * @property Member $Member
 * @property Member $Member_2
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method integer getMemberIdFrom()   Returns the current record's "member_id_from" value
 * @method integer getMemberIdTo()     Returns the current record's "member_id_to" value
 * @method date    getRDate()          Returns the current record's "r_date" value
 * @method Member  getMember()         Returns the current record's "Member" value
 * @method Member  getMember2()        Returns the current record's "Member_2" value
 * @method Ashiato setId()             Sets the current record's "id" value
 * @method Ashiato setMemberIdFrom()   Sets the current record's "member_id_from" value
 * @method Ashiato setMemberIdTo()     Sets the current record's "member_id_to" value
 * @method Ashiato setRDate()          Sets the current record's "r_date" value
 * @method Ashiato setMember()         Sets the current record's "Member" value
 * @method Ashiato setMember2()        Sets the current record's "Member_2" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAshiato extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ashiato');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id_from', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('member_id_to', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('r_date', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id_to',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('Member as Member_2', array(
             'local' => 'member_id_from',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}