<?php

/**
 * BaseMessageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type_name
 * @property string $foreign_table
 * @property boolean $is_deleted
 * @property string $body
 * @property string $subject
 * @property string $caption
 * @property string $info
 * @property Doctrine_Collection $SendMessageData
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getTypeName()        Returns the current record's "type_name" value
 * @method string              getForeignTable()    Returns the current record's "foreign_table" value
 * @method boolean             getIsDeleted()       Returns the current record's "is_deleted" value
 * @method string              getBody()            Returns the current record's "body" value
 * @method string              getSubject()         Returns the current record's "subject" value
 * @method string              getCaption()         Returns the current record's "caption" value
 * @method string              getInfo()            Returns the current record's "info" value
 * @method Doctrine_Collection getSendMessageData() Returns the current record's "SendMessageData" collection
 * @method MessageType         setId()              Sets the current record's "id" value
 * @method MessageType         setTypeName()        Sets the current record's "type_name" value
 * @method MessageType         setForeignTable()    Sets the current record's "foreign_table" value
 * @method MessageType         setIsDeleted()       Sets the current record's "is_deleted" value
 * @method MessageType         setBody()            Sets the current record's "body" value
 * @method MessageType         setSubject()         Sets the current record's "subject" value
 * @method MessageType         setCaption()         Sets the current record's "caption" value
 * @method MessageType         setInfo()            Sets the current record's "info" value
 * @method MessageType         setSendMessageData() Sets the current record's "SendMessageData" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMessageType extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('type_name', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '256',
             ));
        $this->hasColumn('foreign_table', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_deleted', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => 'ture',
             'default' => 0,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('subject', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('caption', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('info', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SendMessageData', array(
             'local' => 'id',
             'foreign' => 'message_type_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'caption',
              1 => 'info',
              2 => 'body',
              3 => 'subject',
             ),
             'length' => 5,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}