<?php

/**
 * BaseMessageFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_id
 * @property integer $file_id
 * @property SendMessageData $SendMessageData
 * @property File $File
 * 
 * @method integer         getId()              Returns the current record's "id" value
 * @method integer         getMessageId()       Returns the current record's "message_id" value
 * @method integer         getFileId()          Returns the current record's "file_id" value
 * @method SendMessageData getSendMessageData() Returns the current record's "SendMessageData" value
 * @method File            getFile()            Returns the current record's "File" value
 * @method MessageFile     setId()              Sets the current record's "id" value
 * @method MessageFile     setMessageId()       Sets the current record's "message_id" value
 * @method MessageFile     setFileId()          Sets the current record's "file_id" value
 * @method MessageFile     setSendMessageData() Sets the current record's "SendMessageData" value
 * @method MessageFile     setFile()            Sets the current record's "File" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMessageFile extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message_file');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('message_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SendMessageData', array(
             'local' => 'message_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}