<?php

/**
 * BaseSendMessageData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property string $subject
 * @property string $body
 * @property boolean $is_deleted
 * @property boolean $is_send
 * @property integer $thread_message_id
 * @property integer $return_message_id
 * @property integer $message_type_id
 * @property integer $foreign_id
 * @property Member $Member
 * @property MessageType $MessageType
 * @property Doctrine_Collection $MessageFile
 * @property Doctrine_Collection $MessageSendList
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getMemberId()          Returns the current record's "member_id" value
 * @method string              getSubject()           Returns the current record's "subject" value
 * @method string              getBody()              Returns the current record's "body" value
 * @method boolean             getIsDeleted()         Returns the current record's "is_deleted" value
 * @method boolean             getIsSend()            Returns the current record's "is_send" value
 * @method integer             getThreadMessageId()   Returns the current record's "thread_message_id" value
 * @method integer             getReturnMessageId()   Returns the current record's "return_message_id" value
 * @method integer             getMessageTypeId()     Returns the current record's "message_type_id" value
 * @method integer             getForeignId()         Returns the current record's "foreign_id" value
 * @method Member              getMember()            Returns the current record's "Member" value
 * @method MessageType         getMessageType()       Returns the current record's "MessageType" value
 * @method Doctrine_Collection getMessageFile()       Returns the current record's "MessageFile" collection
 * @method Doctrine_Collection getMessageSendList()   Returns the current record's "MessageSendList" collection
 * @method SendMessageData     setId()                Sets the current record's "id" value
 * @method SendMessageData     setMemberId()          Sets the current record's "member_id" value
 * @method SendMessageData     setSubject()           Sets the current record's "subject" value
 * @method SendMessageData     setBody()              Sets the current record's "body" value
 * @method SendMessageData     setIsDeleted()         Sets the current record's "is_deleted" value
 * @method SendMessageData     setIsSend()            Sets the current record's "is_send" value
 * @method SendMessageData     setThreadMessageId()   Sets the current record's "thread_message_id" value
 * @method SendMessageData     setReturnMessageId()   Sets the current record's "return_message_id" value
 * @method SendMessageData     setMessageTypeId()     Sets the current record's "message_type_id" value
 * @method SendMessageData     setForeignId()         Sets the current record's "foreign_id" value
 * @method SendMessageData     setMember()            Sets the current record's "Member" value
 * @method SendMessageData     setMessageType()       Sets the current record's "MessageType" value
 * @method SendMessageData     setMessageFile()       Sets the current record's "MessageFile" collection
 * @method SendMessageData     setMessageSendList()   Sets the current record's "MessageSendList" collection
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSendMessageData extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('subject', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_deleted', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_send', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('thread_message_id', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('return_message_id', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('message_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('foreign_id', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasOne('MessageType', array(
             'local' => 'message_type_id',
             'foreign' => 'id'));

        $this->hasMany('MessageFile', array(
             'local' => 'id',
             'foreign' => 'message_id'));

        $this->hasMany('MessageSendList', array(
             'local' => 'id',
             'foreign' => 'message_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}