<?php

/**
 * BaseMemberApplicationSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_application_id
 * @property enum $type
 * @property string $name
 * @property string $hash
 * @property string $value
 * @property MemberApplication $MemberApplication
 * 
 * @method integer                  getMemberApplicationId()   Returns the current record's "member_application_id" value
 * @method enum                     getType()                  Returns the current record's "type" value
 * @method string                   getName()                  Returns the current record's "name" value
 * @method string                   getHash()                  Returns the current record's "hash" value
 * @method string                   getValue()                 Returns the current record's "value" value
 * @method MemberApplication        getMemberApplication()     Returns the current record's "MemberApplication" value
 * @method MemberApplicationSetting setMemberApplicationId()   Sets the current record's "member_application_id" value
 * @method MemberApplicationSetting setType()                  Sets the current record's "type" value
 * @method MemberApplicationSetting setName()                  Sets the current record's "name" value
 * @method MemberApplicationSetting setHash()                  Sets the current record's "hash" value
 * @method MemberApplicationSetting setValue()                 Sets the current record's "value" value
 * @method MemberApplicationSetting setMemberApplication()     Sets the current record's "MemberApplication" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMemberApplicationSetting extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_application_setting');
        $this->hasColumn('member_application_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'application',
              1 => 'user',
             ),
             'notnull' => true,
             'default' => 'application',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('hash', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '32',
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('hash_UNIQUE', array(
             'fields' => 
             array(
              0 => 'hash',
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MemberApplication', array(
             'local' => 'member_application_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}