<?php

/**
 * BaseApplicationInvite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $application_id
 * @property integer $to_member_id
 * @property integer $from_member_id
 * @property Application $Application
 * @property Member $ToMember
 * @property Member $FromMember
 * 
 * @method integer           getApplicationId()  Returns the current record's "application_id" value
 * @method integer           getToMemberId()     Returns the current record's "to_member_id" value
 * @method integer           getFromMemberId()   Returns the current record's "from_member_id" value
 * @method Application       getApplication()    Returns the current record's "Application" value
 * @method Member            getToMember()       Returns the current record's "ToMember" value
 * @method Member            getFromMember()     Returns the current record's "FromMember" value
 * @method ApplicationInvite setApplicationId()  Sets the current record's "application_id" value
 * @method ApplicationInvite setToMemberId()     Sets the current record's "to_member_id" value
 * @method ApplicationInvite setFromMemberId()   Sets the current record's "from_member_id" value
 * @method ApplicationInvite setApplication()    Sets the current record's "Application" value
 * @method ApplicationInvite setToMember()       Sets the current record's "ToMember" value
 * @method ApplicationInvite setFromMember()     Sets the current record's "FromMember" value
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseApplicationInvite extends opDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('application_invite');
        $this->hasColumn('application_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('to_member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('from_member_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Application', array(
             'local' => 'application_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Member as ToMember', array(
             'local' => 'to_member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Member as FromMember', array(
             'local' => 'from_member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}